name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  bt-product-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # pull代码到运行服务器上
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com # 镜像容器服务登录地址
        region-id: cn-hangzhou # 镜像容器服务登录地址
        username: "${{ secrets.REGISTRY_USERNAME }}" # GitHub repo设置的镜像容器服务用户名
        password: "${{ secrets.REGISTRY_PASSWORD }}" # GitHub repo设置的镜像容器服务密码
    - name: Build and Push Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }} # 容器版本号
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/xxh-test/go-test:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/xxh-test/go-test:$IMAGE_TAG

